# Generated by Django 3.0.5 on 2020-06-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassesForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofclass', models.CharField(max_length=60)),
                ('monthlyfees', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='edsystango',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='edsystango',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
