# Generated by Django 3.0.5 on 2020-06-16 09:14

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('edApp', '0002_auto_20200612_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Yourinstituename', models.CharField(max_length=60)),
                ('Targetline', models.CharField(max_length=60)),
                ('Institutelogo', models.FileField(upload_to='images/')),
                ('Phone', models.CharField(max_length=12)),
                ('Wedsite', models.CharField(max_length=60)),
                ('Address', models.CharField(max_length=60)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
    ]
