# Generated by Django 3.0.5 on 2020-06-21 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edApp', '0003_instituteform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instituteform',
            old_name='Wedsite',
            new_name='Website',
        ),
    ]
