# Generated by Django 3.0.5 on 2020-06-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edApp', '0004_auto_20200621_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='feesForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admissionfee', models.CharField(max_length=60)),
                ('Registrationfee', models.IntegerField(max_length=20)),
                ('Art_material', models.CharField(max_length=60)),
                ('Transport', models.CharField(max_length=60)),
                ('Books', models.CharField(max_length=60)),
                ('Uniform', models.CharField(max_length=60)),
                ('Fine', models.CharField(max_length=60)),
                ('Others', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='rulesForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
